# Generated by Django 5.1.6 on 2025-02-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hospitalapp', '0004_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
